-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.event_categories
(
    id serial NOT NULL,
    name character varying(200) COLLATE pg_catalog."default",
    display_order integer,
    CONSTRAINT event_categories_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.event_enrollments
(
    id serial,
    id_event serial,
    id_user serial,
    description character varying(250) COLLATE pg_catalog."default",
    registration_date_time date,
    attended boolean,
    observations character varying(300) COLLATE pg_catalog."default",
    rating integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.event_locations
(
    id serial,
    id_location serial,
    name character varying(30) COLLATE pg_catalog."default",
    full_address character varying(100) COLLATE pg_catalog."default",
    max_capacity integer,
    latitude integer,
    longitude integer,
    id_creator_user serial,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.event_tags
(
    id serial NOT NULL,
    id_event serial,
    id_tag serial,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.events
(
    id serial,
    name character varying(86) COLLATE pg_catalog."default",
    description character varying(300) COLLATE pg_catalog."default",
    id_event_category serial,
    id_event_location serial,
    start_date date,
    duration_in_minutes double precision,
    price double precision,
    enabled_for_enrollment boolean,
    max_assistance integer,
    id_creator_user serial,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.locations
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default",
    id_province serial,
    latitude integer,
    longitude integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.provinces
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default",
    full_name character varying(150) COLLATE pg_catalog."default",
    latitude integer,
    longitude integer,
    display_order integer,
    CONSTRAINT provinces_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tags
(
    id serial NOT NULL,
    name character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT tags_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    first_name character varying(80) COLLATE pg_catalog."default",
    last_name character varying(74) COLLATE pg_catalog."default",
    username character varying(20) COLLATE pg_catalog."default",
    password character varying(25) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id)
);
END;